from enum import StrEnum


class BadgeCode(StrEnum):
    ON_TIME_SCHOLAR = "ON_TIME_SCHOLAR"
    CONSISTENCY_CHAMPION = "CONSISTENCY_CHAMPION"
    SKILL_MASTER = "SKILL_MASTER"


RISK_THRESHOLD_LOW = 20
RISK_THRESHOLD_MEDIUM = 45
RISK_THRESHOLD_HIGH = 70
