from __future__ import annotations

from dataclasses import dataclass

from app.models.iam import ScopeType


@dataclass(frozen=True, slots=True)
class RoleDefinition:
    code: str
    description: str
    scope_type: str
    permissions: tuple[str, ...]


PERMISSION_DEFINITIONS: dict[str, str] = {
    "admin.conflicts": "Resolve sync conflicts",
    "admin.receipts": "Inspect receipt chains",
    "assessment.create": "Create and configure assessments",
    "assessment.read": "View assessments in scope",
    "assessment.submit": "Attempt and submit assessments",
    "content.pin": "Pin resources for offline usage",
    "content.read": "View published learning resources",
    "content.write": "Create and update learning resources",
    "course.read": "View courses in scope",
    "course.write": "Create and update courses",
    "enrollment.manage": "Manage course enrollments",
    "exam.appeal.manage": "Manage exam disputes and appeals",
    "exam.results.read": "Read examination results",
    "exam.schedule.manage": "Create and maintain exam schedules",
    "grade.override": "Override grades after dispute review",
    "grade.release": "Release grades to students",
    "grade.view": "View grades in scope",
    "helpdesk.create": "Create helpdesk tickets",
    "helpdesk.read.own": "View own helpdesk tickets",
    "helpdesk.read.scope": "View helpdesk tickets in scope",
    "helpdesk.resolve": "Resolve helpdesk tickets in scope",
    "map.read": "Use campus map features",
    "notification.create": "Send notifications in scope",
    "notification.read.own": "Read own notifications",
    "receipt.read.own": "Read own receipts",
    "receipt.read.scope": "Read receipt chains in scope",
    "receipt.verify.public": "Verify receipt authenticity",
    "student_success.read.own": "View own student-success signals",
    "student_success.read.scope": "View student-success data in scope",
    "submission.grade": "Grade assessment submissions",
    "sync.batch.submit": "Submit offline sync batches",
    "sync.conflicts.read.own": "View own sync conflicts",
    "sync.conflicts.resolve.own": "Resolve own sync conflicts",
    "system.feature_flags.manage": "Configure feature flags and policies",
    "system.integrations.manage": "Configure technical integrations",
    "system.logs.read": "View system logs and metrics",
    "system.users_roles.manage": "Manage users, roles, and bindings",
    "timetable.read": "View timetable events",
    "timetable.write": "Create and edit timetable events",
    "transcript.export": "Export official transcripts",
}


ROLE_DEFINITIONS: tuple[RoleDefinition, ...] = (
    RoleDefinition(
        code="super_admin",
        description="Institution super administrator",
        scope_type=ScopeType.INSTITUTION.value,
        permissions=tuple(PERMISSION_DEFINITIONS.keys()),
    ),
    RoleDefinition(
        code="ict_admin",
        description="Institution ICT administrator",
        scope_type=ScopeType.INSTITUTION.value,
        permissions=(
            "admin.conflicts",
            "helpdesk.read.scope",
            "helpdesk.resolve",
            "map.read",
            "receipt.verify.public",
            "system.integrations.manage",
            "system.logs.read",
        ),
    ),
    RoleDefinition(
        code="exam_officer",
        description="Institution examination officer",
        scope_type=ScopeType.INSTITUTION.value,
        permissions=(
            "exam.appeal.manage",
            "exam.results.read",
            "exam.schedule.manage",
            "grade.override",
            "grade.release",
            "grade.view",
            "receipt.read.scope",
            "receipt.verify.public",
            "timetable.read",
            "timetable.write",
            "transcript.export",
        ),
    ),
    RoleDefinition(
        code="college_admin",
        description="College-level administrator",
        scope_type=ScopeType.COLLEGE.value,
        permissions=(
            "course.read",
            "enrollment.manage",
            "grade.override",
            "grade.view",
            "helpdesk.read.scope",
            "helpdesk.resolve",
            "receipt.read.scope",
            "receipt.verify.public",
            "student_success.read.scope",
            "system.users_roles.manage",
            "timetable.read",
            "timetable.write",
        ),
    ),
    RoleDefinition(
        code="college_exam_officer",
        description="College-level examination officer",
        scope_type=ScopeType.COLLEGE.value,
        permissions=(
            "exam.results.read",
            "exam.schedule.manage",
            "grade.view",
            "map.read",
            "receipt.verify.public",
            "timetable.read",
            "timetable.write",
        ),
    ),
    RoleDefinition(
        code="hod",
        description="Head of department",
        scope_type=ScopeType.DEPARTMENT.value,
        permissions=(
            "assessment.create",
            "assessment.read",
            "content.read",
            "content.write",
            "course.read",
            "course.write",
            "enrollment.manage",
            "grade.override",
            "grade.release",
            "grade.view",
            "helpdesk.read.scope",
            "helpdesk.resolve",
            "receipt.read.scope",
            "receipt.verify.public",
            "student_success.read.scope",
            "submission.grade",
            "timetable.read",
            "timetable.write",
        ),
    ),
    RoleDefinition(
        code="dept_admin",
        description="Department administrator",
        scope_type=ScopeType.DEPARTMENT.value,
        permissions=(
            "course.read",
            "enrollment.manage",
            "helpdesk.read.scope",
            "receipt.verify.public",
            "timetable.read",
            "timetable.write",
        ),
    ),
    RoleDefinition(
        code="lecturer",
        description="Course lecturer",
        scope_type=ScopeType.COURSE.value,
        permissions=(
            "assessment.create",
            "assessment.read",
            "content.pin",
            "content.read",
            "content.write",
            "course.read",
            "grade.release",
            "grade.view",
            "helpdesk.read.scope",
            "helpdesk.resolve",
            "map.read",
            "notification.create",
            "notification.read.own",
            "receipt.read.own",
            "receipt.verify.public",
            "student_success.read.own",
            "student_success.read.scope",
            "submission.grade",
            "timetable.read",
        ),
    ),
    RoleDefinition(
        code="ta",
        description="Teaching assistant",
        scope_type=ScopeType.COURSE.value,
        permissions=(
            "assessment.read",
            "content.pin",
            "content.read",
            "course.read",
            "grade.view",
            "helpdesk.read.scope",
            "helpdesk.resolve",
            "map.read",
            "notification.read.own",
            "receipt.read.own",
            "receipt.verify.public",
            "student_success.read.own",
            "submission.grade",
            "timetable.read",
        ),
    ),
    RoleDefinition(
        code="student",
        description="Student user",
        scope_type=ScopeType.COURSE.value,
        permissions=(
            "assessment.read",
            "assessment.submit",
            "content.pin",
            "content.read",
            "course.read",
            "grade.view",
            "helpdesk.create",
            "helpdesk.read.own",
            "map.read",
            "notification.read.own",
            "receipt.read.own",
            "receipt.verify.public",
            "student_success.read.own",
            "sync.batch.submit",
            "sync.conflicts.read.own",
            "sync.conflicts.resolve.own",
            "timetable.read",
        ),
    ),
    RoleDefinition(
        code="external_examiner",
        description="External course examiner (read-only)",
        scope_type=ScopeType.COURSE.value,
        permissions=(
            "assessment.read",
            "content.read",
            "course.read",
            "exam.results.read",
            "grade.view",
            "receipt.verify.public",
            "timetable.read",
        ),
    ),
    RoleDefinition(
        code="guest",
        description="Guest public session role",
        scope_type=ScopeType.COURSE.value,
        permissions=(
            "content.read",
            "map.read",
            "receipt.verify.public",
            "timetable.read",
        ),
    ),
)


ROLE_DEFINITIONS_BY_CODE: dict[str, RoleDefinition] = {role.code: role for role in ROLE_DEFINITIONS}
